#!/bin/sh
screen -dmS core01scr
screen -dmS core02scr
screen -dmS core03scr
screen -dmS core04scr
screen -dmS core05scr
screen -dmS core06scr
screen -dmS core07scr
screen -dmS core08scr
screen -dmS core09scr
screen -dmS core10scr
screen -dmS core11scr
screen -dmS core12scr
screen -dmS core13scr
screen -dmS core14scr
screen -dmS core15scr
screen -dmS core16scr
screen -dmS core17scr
screen -dmS core18scr
screen -dmS core19scr
screen -dmS core20scr
screen -dmS core21scr
screen -dmS core22scr
screen -dmS core23scr
screen -dmS core24scr
screen -dmS core25scr
screen -dmS core26scr
screen -dmS core27scr
screen -dmS core28scr
screen -dmS core29scr
screen -dmS core30scr