#!/bin/sh
screen -dmS core1  bash -c 'source $HOME/.profile; ./runcore1.sh: exec sh'
screen -dmS core2  bash -c 'source $HOME/.profile; ./runcore2.sh: exec sh'
screen -dmS core3  bash -c 'source $HOME/.profile; ./runcore3.sh: exec sh'
screen -dmS core4  bash -c 'source $HOME/.profile; ./runcore4.sh: exec sh'
screen -dmS core5  bash -c 'source $HOME/.profile; ./runcore5.sh: exec sh'
screen -dmS core6  bash -c 'source $HOME/.profile; ./runcore6.sh: exec sh'
screen -dmS core7  bash -c 'source $HOME/.profile; ./runcore7.sh: exec sh'
screen -dmS core8  bash -c 'source $HOME/.profile; ./runcore8.sh: exec sh'
screen -dmS core9  bash -c 'source $HOME/.profile; ./runcore9.sh: exec sh'
screen -dmS core10 bash -c 'source $HOME/.profile; ./runcore10.sh: exec sh'
screen -dmS core11 bash -c 'source $HOME/.profile; ./runcore11.sh: exec sh'
screen -dmS core12 bash -c 'source $HOME/.profile; ./runcore12.sh: exec sh'
screen -dmS core13 bash -c 'source $HOME/.profile; ./runcore13.sh: exec sh'
screen -dmS core14 bash -c 'source $HOME/.profile; ./runcore14.sh: exec sh'
screen -dmS core15 bash -c 'source $HOME/.profile; ./runcore15.sh: exec sh'
screen -dmS core16 bash -c 'source $HOME/.profile; ./runcore16.sh: exec sh'

